---
on: [push, pull_request]
name: Build
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.x, 1.18.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: git submodule init && git submodule update
      - name: Install automake on macOS
        if: runner.os == 'macOS'
        run: brew install automake
      - run: make
      - run: ./tau --help
