name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./tau-linux-aarch64
            ./tau-linux-x86_64
            ./tau-macos-aarch64
            ./tau-macos-x86_64
#           ./tau-windows-x86_64
          repo_token: ${{ secrets.GITHUB_TOKEN }}
